spring.application.name=fontanero
spring.thymeleaf.enabled=false

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

spring.main.allow-bean-definition-overriding=true

server.error.include-exception=true
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
server.error.path=/error

logging.level.org.springframework.security=DEBUG

spring.data.mongodb.uri=${DB_URL}
spring.data.mongodb.host=192.168.0.xx 
spring.data.mongodb.port=27017
spring.data.mongodb.database=fontanero
spring.data.mongodb.username=${DB_ID}
spring.data.mongodb.password=${DB_PW}
spring.data.mongodb.authentication-database=admin 

spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false
spring.jackson.time-zone=Europe/Madrid
spring.data.mongodb.auto-index-creation=true


telegram.bot.token=${TELE_TOKEN}
telegram.chat.id=${CHAT_ID}